config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources :user_stocks, except: [:show, :edit, :update]
  resources :users, only: [:show]
  resources :friendships

  root 'welcome#index'
  get 'my_portfolio', to: "users#my_portfolio"
  get 'search_stocks', to: "stocks#search"
  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  
  has_many :user_stocks
  has_many :users, through: :user_stocks
  
  #Este metodo busca un objeto ticker en nuestra tabla de Stocks
  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
  
  #Recordar que def self.nombre_del_metodo se utiliza para nombrar metodos de clase.
  #Este metodo retorna un objeto ticker, con informacion real de stock sobre lo que le pasemos
  #como parametro.
  def self.new_from_lookup(ticker_symbol)
    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
    return nil unless looked_up_stock.name
    
    new_stock = new(ticker: looked_up_stock.symbol, name: looked_up_stock.name)
    new_stock.last_price = new_stock.price
    new_stock
  end
    
  def price
    #Busca si closing_price no es nil
    closing_price = StockQuote::Stock.quote(ticker).close
    return "#{closing_price} (Closing)" if closing_price
    
    #Si lo es, busca si opening_price no es nil
    opening_price = StockQuote::Stock.quote(ticker).open
    return "#{opening_price} (Opening)" if opening_price
    #Si lo es, entonces simplemente retorna unavailable
    'Unavailable'
  end
  
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  
  def search
    if params[:stock]
      @stock = Stock.find_by_ticker(params[:stock])
      #Recordar que esta funciona de la siguiente manera, si @stock es nil, entonces ejecutara el
      #metodo new_from_lookup, de lo contrario, solo tomara el objeto @stock
      @stock ||= Stock.new_from_lookup(params[:stock])
    end
    
    if @stock
      #render json: @stock
      render partial: 'lookup'
    else
      render status: :not_found, nothing: true
    end
  end
  

end

app/views/stocks/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current Price</th>
      <% if @user.id == current_user.id %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @user_stocks.each do |user_stock| %>
      <tr>
        <td><%= user_stock.name %></td>
        <td><%= user_stock.ticker %></td>
        <td><%= user_stock.price %></td>
        <% if @user.id == current_user.id %>
          <td>
            <%= link_to 'Delete', user_stock_path(user_stock),
                                  :method => :delete,
                                  :data => { :confirm => "Are you sure?" },
                                  :class => "btn btn-xs btn-danger" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stocks/_lookup.html.erb
<!-- Este es un form construido manualmente, no por medio de form-for -->
<div id="stock-lookup">
  <h3>Search for Stocks</h3>
  <!-- Esto sera manejado por medio de Ajax, por eso lo extraño de la sintaxis -->
  <%= form_tag search_stocks_path, remote: true, method: :get, id: 'stock-lookup-form' do %>
   
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true,
                                   class: 'form-control search-box input-lg' %>
      </div>
     
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <!-- La i class de bootstrap -->
          <i class="fa fa-search"></i> Look up a stock
        <% end %>
      </div>
    </div>
 
 <% end %>
 <%= render 'common/spinner' %>
 <% if @stock %>
  <div id="stock-lookup-results" class="well results-block">
    <strong>Symbol:</strong> <%= @stock.ticker %>
    <strong>Name:</strong> <%= @stock.name %>
    <strong>Price:</strong> <%= @stock.price %>
    <% if current_user.can_add_stock?(@stock.ticker) %>
      <%= link_to "Add to my Stocks", user_stocks_path(user: current_user, stock_ticker: @stock.ticker,
                                                       stock_id: @stock.id ? @stock.id: ''), class: 'btn btn-xs btn-success',
                                                       method: :post %>
    <% else %>
      <span class="label label-default">
        Stock cannot be added because you have already added
        <% if !current_user.under_stock_limit? %>
          10 stocks
        <% end %>
        <% if current_user.stock_already_added?(@stock.ticker) %>
          this stock
        <% end %>
      </span>
    <% end %>
  </div>
 <% end %>
 <div id='stock-lookup-errors'></div>
 
</div>